/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as NmeictRouteImport } from './routes/nmeict'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsLabIdRouteImport } from './routes/labs.$labId'
import { Route as BroadAreasAreaRouteImport } from './routes/broad-areas.$area'
import { Route as LabsLabIdExperimentsExpIdRouteImport } from './routes/labs.$labId.experiments.$expId'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const NmeictRoute = NmeictRouteImport.update({
  id: '/nmeict',
  path: '/nmeict',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdRoute = LabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadAreasAreaRoute = BroadAreasAreaRouteImport.update({
  id: '/broad-areas/$area',
  path: '/broad-areas/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdExperimentsExpIdRoute =
  LabsLabIdExperimentsExpIdRouteImport.update({
    id: '/experiments/$expId',
    path: '/experiments/$expId',
    getParentRoute: () => LabsLabIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/nmeict': typeof NmeictRoute
  '/outreach': typeof OutreachRoute
  '/partners': typeof PartnersRoute
  '/broad-areas/$area': typeof BroadAreasAreaRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/$labId/experiments/$expId': typeof LabsLabIdExperimentsExpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/nmeict': typeof NmeictRoute
  '/outreach': typeof OutreachRoute
  '/partners': typeof PartnersRoute
  '/broad-areas/$area': typeof BroadAreasAreaRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/$labId/experiments/$expId': typeof LabsLabIdExperimentsExpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/nmeict': typeof NmeictRoute
  '/outreach': typeof OutreachRoute
  '/partners': typeof PartnersRoute
  '/broad-areas/$area': typeof BroadAreasAreaRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/$labId/experiments/$expId': typeof LabsLabIdExperimentsExpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/nmeict'
    | '/outreach'
    | '/partners'
    | '/broad-areas/$area'
    | '/labs/$labId'
    | '/labs/$labId/experiments/$expId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/nmeict'
    | '/outreach'
    | '/partners'
    | '/broad-areas/$area'
    | '/labs/$labId'
    | '/labs/$labId/experiments/$expId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/nmeict'
    | '/outreach'
    | '/partners'
    | '/broad-areas/$area'
    | '/labs/$labId'
    | '/labs/$labId/experiments/$expId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  NmeictRoute: typeof NmeictRoute
  OutreachRoute: typeof OutreachRoute
  PartnersRoute: typeof PartnersRoute
  BroadAreasAreaRoute: typeof BroadAreasAreaRoute
  LabsLabIdRoute: typeof LabsLabIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nmeict': {
      id: '/nmeict'
      path: '/nmeict'
      fullPath: '/nmeict'
      preLoaderRoute: typeof NmeictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId': {
      id: '/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof LabsLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broad-areas/$area': {
      id: '/broad-areas/$area'
      path: '/broad-areas/$area'
      fullPath: '/broad-areas/$area'
      preLoaderRoute: typeof BroadAreasAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId/experiments/$expId': {
      id: '/labs/$labId/experiments/$expId'
      path: '/experiments/$expId'
      fullPath: '/labs/$labId/experiments/$expId'
      preLoaderRoute: typeof LabsLabIdExperimentsExpIdRouteImport
      parentRoute: typeof LabsLabIdRoute
    }
  }
}

interface LabsLabIdRouteChildren {
  LabsLabIdExperimentsExpIdRoute: typeof LabsLabIdExperimentsExpIdRoute
}

const LabsLabIdRouteChildren: LabsLabIdRouteChildren = {
  LabsLabIdExperimentsExpIdRoute: LabsLabIdExperimentsExpIdRoute,
}

const LabsLabIdRouteWithChildren = LabsLabIdRoute._addFileChildren(
  LabsLabIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  NmeictRoute: NmeictRoute,
  OutreachRoute: OutreachRoute,
  PartnersRoute: PartnersRoute,
  BroadAreasAreaRoute: BroadAreasAreaRoute,
  LabsLabIdRoute: LabsLabIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
